name: Android CI

on:
  push:
    branches: ["main"]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - 'libs.versions.toml'
      - '.github/workflows/android_ci.yml'
  pull_request:
    branches: ["main"]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'gradle/**'
      - 'libs.versions.toml'
      - '.github/workflows/android_ci.yml'
  workflow_dispatch: # Allow manual triggers

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK
        run: |
          # GitHub Actions provides Android SDK pre-installed
          echo "ANDROID_HOME=$ANDROID_HOME"
          
          # Accept licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          
          # Install required SDK components
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      # Temporarily disabled due to network connectivity issues
      # - name: Validate Gradle wrapper
      #   uses: gradle/wrapper-validation-action@v3

      - name: Grant execute permission for gradlew and lint scripts
        run: |
          chmod +x gradlew
          chmod +x lint-summary.sh

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Run Android Lint
        run: ./lint-summary.sh

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --continue

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error # Fails the workflow if APK is not found
          retention-days: 7

      - name: Upload Lint reports
        uses: actions/upload-artifact@v4
        if: always() # Upload reports even if previous steps fail
        with:
          name: lint-reports
          path: |
            app/build/reports/lint-results-debug.xml
            app/build/reports/lint-results-debug.html
          if-no-files-found: ignore # Don't fail if report is not found (e.g., no lint issues)
          retention-days: 7

      - name: Upload Unit Test reports
        uses: actions/upload-artifact@v4
        if: always() # Upload reports even if previous steps fail
        with:
          name: unit-test-reports
          path: app/build/reports/tests/testDebugUnitTest/
          if-no-files-found: ignore # Don't fail if reports are not found (e.g., no tests yet)
          retention-days: 7
