name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: com.android.tools.build:setup-android@v3.0.0 # Using the official Android tools action
      with:
        api-level: 35 # Matches compileSdk from build.gradle.kts
        # ndk-version: # Optional: specify NDK version if needed
        # build-tools-version: # Optional: specify build tools version if needed

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Android Lint
      run: ./gradlew lintDebug

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        if-no-files-found: error # Fails the workflow if APK is not found

    - name: Upload Lint reports
      uses: actions/upload-artifact@v4
      if: always() # Upload reports even if previous steps fail
      with:
        name: lint-reports
        path: app/build/reports/lint-results-debug.xml
        if-no-files-found: ignore # Don't fail if report is not found (e.g., no lint issues)

    - name: Upload Unit Test reports
      uses: actions/upload-artifact@v4
      if: always() # Upload reports even if previous steps fail
      with:
        name: unit-test-reports
        path: app/build/reports/tests/testDebugUnitTest/
        if-no-files-found: ignore # Don't fail if reports are not found (e.g., no tests yet)
