name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: |
            tools
            platform-tools
            platforms;android-35
            build-tools;35.0.0

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Android Lint
        run: ./gradlew lintDebug

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --continue || true

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error # Fails the workflow if APK is not found

      - name: Upload Lint reports
        uses: actions/upload-artifact@v4
        if: always() # Upload reports even if previous steps fail
        with:
          name: lint-reports
          path: |
            app/build/reports/lint-results-debug.xml
            app/build/reports/lint-results-debug.html
          if-no-files-found: ignore # Don't fail if report is not found (e.g., no lint issues)

      - name: Upload Unit Test reports
        uses: actions/upload-artifact@v4
        if: always() # Upload reports even if previous steps fail
        with:
          name: unit-test-reports
          path: app/build/reports/tests/testDebugUnitTest/
          if-no-files-found: ignore # Don't fail if reports are not found (e.g., no tests yet)
