name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.CLAUDE_API_KEY }}
          direct_prompt: |
            **Overview Analysis:**
            - What this PR accomplishes
            - Analysis of code quality and style
            - Specific suggestions for improvements
            - Any potential issues or risks
            
            **Multi-Agent Verification:**
            - Check if Testing Agent deliverables are present (new/updated tests in the diff)
            - Check if Documentation Agent deliverables are present (updated docs, comments, README changes)
            - Verify that planned multi-agent coordination actually happened
            - Note any missing agent deliverables
            
            **Focus Areas:**
            - Code correctness and Android TV/Kotlin best practices
            - Following Jetpack Compose conventions
            - Performance implications for TV hardware
            - Test coverage and quality
            - Security considerations for Real Debrid integration
            
            **Android TV Specific Checks:**
            - Focus navigation implementation
            - Leanback library usage
            - TV-optimized UI patterns
            - Remote control input handling
            
            **TODO/Issue Management:**
            - Search for TODO, FIXME, HACK comments in changes
            - Identify incomplete work or follow-up items
            - Note any technical debt introduced
            
            Format your review with clear sections and bullet points. Keep feedback constructive and actionable.
            
            Be thorough but concise - focus on meaningful improvements that enhance the Android TV streaming experience.
